function Import-DhcpReservation {
    <#
    .SYNOPSIS
    Imports DHCPv4 reservations from a CSV file.

    .DESCRIPTION
    Imports the CSV generated by Export-DhcpReservation. By default each row is restored
    to its original ScopeId. Use -DestinationScope to redirect all rows to one scope.
    Existing reservations with the same IP address are skipped unless -ErrorOnExisting is used.

    .EXAMPLE
    Import-DhcpReservation -Path .\reservations.csv -ComputerName V08 -WhatIf

    .EXAMPLE
    Import-DhcpReservation -Path .\reservations.csv -DestinationScope 10.10.205.0 -WhatIf
    #>
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact='Medium')]
    param(
        [Parameter(Mandatory)][ValidateScript({ Test-Path -LiteralPath $_ -PathType Leaf })][string]$Path,
        [string]$DestinationScope,
        [string]$ComputerName = $env:COMPUTERNAME,
        [switch]$ErrorOnExisting,
        [switch]$PassThru
    )

    Test-DhcpAdminPrerequisite
    if ($DestinationScope -and -not (Test-IPv4Address $DestinationScope)) {
        throw "Invalid DestinationScope: $DestinationScope"
    }

    $data = @(Import-Csv -LiteralPath $Path -ErrorAction Stop)
    if ($data.Count -eq 0) {
        Write-Warning "CSV file contains no reservations: $Path"
        return
    }

    $required = @('ScopeId','IPAddress','ClientId','Name','Description','Type')
    $columns = @($data[0].PSObject.Properties.Name)
    $missing = @($required | Where-Object { $_ -notin $columns })
    if ($missing.Count -gt 0) {
        throw "Invalid CSV structure. Missing column(s): $($missing -join ', ')"
    }

    foreach ($r in $data) {
        $scope = if ($DestinationScope) { $DestinationScope } else { [string]$r.ScopeId }
        if (-not (Test-IPv4Address $scope)) {
            Write-Error "Invalid ScopeId '$scope' for reservation '$($r.IPAddress)'."
            continue
        }
        if (-not (Test-IPv4Address ([string]$r.IPAddress))) {
            Write-Error "Invalid reservation IPAddress '$($r.IPAddress)'."
            continue
        }

        $existing = Get-DhcpServerv4Reservation -ComputerName $ComputerName -ScopeId $scope -IPAddress $r.IPAddress -ErrorAction SilentlyContinue
        if ($existing) {
            $message = "Reservation $($r.IPAddress) already exists in scope $scope on $ComputerName."
            if ($ErrorOnExisting) { Write-Error $message } else { Write-Warning "$message Skipping." }
            continue
        }

        $target = "$ComputerName / $scope / $($r.IPAddress) ($($r.Name))"
        if (-not $PSCmdlet.ShouldProcess($target, 'Add DHCPv4 reservation')) { continue }

        $params = @{
            ComputerName = $ComputerName
            ScopeId      = $scope
            IPAddress    = [string]$r.IPAddress
            ClientId     = [string]$r.ClientId
            Name         = [string]$r.Name
            ErrorAction  = 'Stop'
        }
        if (-not [string]::IsNullOrWhiteSpace([string]$r.Description)) { $params.Description = [string]$r.Description }
        if (-not [string]::IsNullOrWhiteSpace([string]$r.Type)) { $params.Type = [string]$r.Type }

        try {
            Add-DhcpServerv4Reservation @params
            Write-Verbose "Added $($r.IPAddress) to scope $scope on $ComputerName."
            if ($PassThru) {
                Get-DhcpServerv4Reservation -ComputerName $ComputerName -ScopeId $scope -IPAddress $r.IPAddress -ErrorAction Stop
            }
        }
        catch {
            Write-Error -ErrorRecord $_
        }
    }
}
