services:
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
