name: Run Script on Push

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  run-script:
    runs-on: debian-latest  # Runs on an Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checks out your repo

      - name: Run the script
        run: ./Bash/Update_Golang.sh  # Executes your script
