name: Restart Windows Service

on:
    push:
      branches:
        - main  # Runs when pushing to the main branch

jobs:
  restart-service:
    runs-on: windows-latest  # Ensure the runner is Windows-based
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restart Windows Service
        run: |
           "& './Powershell/System_Utilities/System-Services/GetSystemInfo.ps1 -ServiceName "spooler"'"
        shell: pwsh
