name: RestartService.ps1 

on:
    push:
      branches:
        - main  # Runs when pushing to the main branch

jobs:
  restart-service:
    runs-on: windows-latest  # Ensure the runner is Windows-based
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restart Windows Service
        run: |
           .\Powershell\System-Utils\System-Services\RestartService.ps1 -ServiceName "spooler"
        shell: pwsh
